version: 2.0

jobs:
  "go-1.13":
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/utahta/pythonbrew
    steps:
      - checkout
      - run:
          name: Run test
          command: |
            make deps
            make test

workflows:
  version: 2
  build:
    jobs:
      - "go-1.13"
